version: '3.*'

services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 1s
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    environment:
      PORT: 5000
      TRANSACTION_SERVICE_PORT: ${TRANSACTION_SERVICE_PORT}
      TRANSACTION_SERVICE_HOST: ${TRANSACTION_SERVICE_HOST}
      FLASK_APP: main
    ports:
      - "${API_PORT}:${API_PORT}"
    depends_on:
      - transaction
  transaction:
    build:
      context: ./transaction_service
      dockerfile: Dockerfile
    environment:
      TRANSACTION_SERVICE_PORT: ${TRANSACTION_SERVICE_PORT}
      TRANSACTION_SERVICE_HOST: "*"
      DB_PORT: ${DB_PORT}
      DB_HOST: ${DB_HOST}
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_NAME: ${POSTGRES_DB}
    ports:
      - "${TRANSACTION_SERVICE_PORT}:${TRANSACTION_SERVICE_PORT}"
    depends_on:
      - db
